import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(process.cwd(), ".env.local") });

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

/**
 * Refine Article with Claude - Steps 3-5 of the workflow
 * 
 * Step 3: Refine with Follow-Up Prompts
 * Step 4: Quality Check
 * Step 5: Final Editing (add screenshots, links, personal touch)
 */

const ARTICLE_SLUG = process.argv[2];

if (!ARTICLE_SLUG) {
  console.error("Usage: npx tsx scripts/refine-article-with-claude.ts <article-slug>");
  console.error("Example: npx tsx scripts/refine-article-with-claude.ts the-problem-why-most-saas-startups-fail-before-they-even-start");
  process.exit(1);
}

async function refineArticle() {
  console.log(`\n🎯 Refining Article: ${ARTICLE_SLUG}\n`);

  const articlePath = join(process.cwd(), "articles", `${ARTICLE_SLUG}.md`);

  if (!require("fs").existsSync(articlePath)) {
    console.error(`❌ Article not found: ${articlePath}`);
    process.exit(1);
  }

  const content = readFileSync(articlePath, "utf-8");
  const { critique } = await import("../src/lib/ai-tools/claude");

  // Step 3: Refine with Follow-Up Prompts
  console.log("📝 Step 3: Refining with Follow-Up Prompts...\n");

  // Check length
  const body = content.replace(/^---\n[\s\S]*?\n---\n/, "");
  const wordCount = body.split(/\s+/).length;
  const targetLength = 1800; // From Article 1 config

  console.log(`   Current length: ${wordCount} words`);
  console.log(`   Target length: ${targetLength} words\n`);

  // Refinement prompt
  const refinementPrompt = `You are refining an article that was generated by Claude. Review the article and improve it according to these guidelines:

**Current Article:**
${content}

**Refinement Tasks:**

1. **Length Adjustment** (if needed):
   - Current: ${wordCount} words, Target: ${targetLength} words
   - ${wordCount < targetLength - 200 ? "Expand with more examples, case studies, or depth" : wordCount > targetLength + 200 ? "Condense while keeping key points" : "Length is good, but enhance quality"}

2. **Tone Adjustment**:
   - Make it more conversational and personal (use "we" and "I")
   - Add more honest, transparent language (acknowledge limitations explicitly)
   - Make it more practical and actionable
   - Ensure humble confidence (confident but not arrogant)

3. **Structure Improvement**:
   - Strengthen the hook in the opening (make it more compelling)
   - Add more specific examples from actual implementation
   - Make takeaways more actionable
   - Improve scannability with better headers

4. **Content Enhancement**:
   - Replace [Company] with "SaaS Starter" or "our product creation engine"
   - Add more specific examples from our actual system (Hub, workflows, documents, rules, agents)
   - Include references to actual files, rules, or components where relevant
   - Make [LINK] placeholders more descriptive (e.g., [LINK: Hub Dashboard])
   - Make [SCREENSHOT] placeholders more descriptive (e.g., [SCREENSHOT: Portfolio Dashboard])

5. **Quality Improvements**:
   - Ensure all claims are evidence-based
   - Add more personal context and experiences
   - Make language more engaging and less generic
   - Remove any marketing language or hype

**Output Format:**
- Return the complete refined article in markdown format
- Keep the frontmatter exactly as is
- Maintain all existing structure
- Improve quality while preserving the core message

**Focus on making this article:**
- More authentic and personal
- More specific with real examples
- More actionable for readers
- Better aligned with Indie Hackers and Hacker News audiences`;

  console.log("🤖 Calling Claude to refine article...\n");

  const result = await critique({
    prompt: refinementPrompt,
    systemPrompt: "You are an expert editor specializing in technical writing for product creation and SaaS. Your edits improve clarity, authenticity, and actionability while maintaining the author's voice and core message.",
    model: "claude-3-opus-20240229",
    maxTokens: 4000,
  });

  if (!result.success || !result.data) {
    console.error("❌ Claude failed to refine article:", result.error);
    process.exit(1);
  }

  const refinedContent = result.data.content;

  // Extract frontmatter from original
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
  const originalFrontmatter = frontmatterMatch ? frontmatterMatch[0] : "";

  // Extract body from refined content
  const refinedBody = refinedContent.replace(/^---\n[\s\S]*?\n---\n/, "");
  
  // Combine frontmatter with refined body
  const finalContent = originalFrontmatter + "\n" + refinedBody;

  // Step 4: Quality Check
  console.log("✅ Step 4: Quality Check...\n");

  const qualityCheckPrompt = `Review this refined article and provide a quality assessment:

${finalContent}

**Quality Checklist:**
- [ ] Length: 1,500-2,500 words (sweet spot)
- [ ] Hook: Strong opening that grabs attention
- [ ] Structure: Clear headers, scannable format
- [ ] Examples: Real examples, not just theory
- [ ] Evidence: Data, metrics, proof points
- [ ] Honesty: Acknowledges limitations, failures
- [ ] Actionable: Readers can apply this
- [ ] Links: [LINK] placeholders are descriptive
- [ ] Screenshots: [SCREENSHOT] placeholders are descriptive
- [ ] Tone: Conversational but professional
- [ ] Voice: Uses "we/I" not "you should"
- [ ] Takeaways: Clear key points at the end

Provide a brief assessment (2-3 sentences) and any critical issues that need fixing.`;

  const qualityResult = await critique({
    prompt: qualityCheckPrompt,
    systemPrompt: "You are a quality assurance reviewer for technical articles. Provide honest, constructive feedback.",
    model: "claude-3-haiku-20240307", // Use cheaper model for quick check
    maxTokens: 500,
  });

  if (qualityResult.success && qualityResult.data) {
    console.log("📋 Quality Assessment:");
    console.log(qualityResult.data.content);
    console.log("\n");
  }

  // Save refined article
  const backupPath = articlePath.replace(".md", ".backup.md");
  writeFileSync(backupPath, content, "utf-8"); // Backup original
  writeFileSync(articlePath, finalContent, "utf-8");

  const finalWordCount = finalContent.replace(/^---\n[\s\S]*?\n---\n/, "").split(/\s+/).length;

  console.log(`✅ Article refined successfully!`);
  console.log(`   Original backed up to: ${backupPath}`);
  console.log(`   Refined article: ${articlePath}`);
  console.log(`   Final length: ${finalWordCount} words`);
  console.log(`   URL: http://localhost:3000/articles/${ARTICLE_SLUG}\n`);

  console.log("📝 Step 5: Final Editing (Manual Steps):\n");
  console.log("   - Review the refined article");
  console.log("   - Replace [LINK] placeholders with actual links");
  console.log("   - Add screenshots where [SCREENSHOT] placeholders are");
  console.log("   - Add your personal touch and authentic voice");
  console.log("   - Verify all claims and examples");
  console.log("   - Final polish (grammar, flow, clarity)\n");
}

refineArticle().catch((error) => {
  console.error("❌ Error refining article:", error);
  process.exit(1);
});

